### ISSUE TITLE
Greenhouse can't harvest Immersive Engineering hemp

### ISSUE THREAD

**Issue by ghost** [SonarSonic/Calculator#189]
Please fill out the details below before contributing

    Forge Version: 12.18.2.2116
    Calculator Version: 1.9.4-3.1.2
    SonarCore Version: 1.9.4-3.1.6
    Multiplayer or Singleplayer: SSP
    Crash Report Link: N/A
    Affected Features: Powering Separator, Greenhouse, Powercube
    Description: I put hemp seeds from IE in the basic greenhouse. They grew, but were never harvested. This probably has something to do with the crops themselves and may not be reasonably resolvable at your end.

**Comment by hron84** [comment]
Maybe @BluSunrize can help.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by Sandriell** [comment]
This bug may have cropped back up. I am using Calculator-1.10.2-3.2.5 and SonarCore-1.10.2-3.2.9 and the greenhouse (basic at least) never harvests Immersive Engineering's hemp.

**Comment by closeshot** [comment]
still having the issue  just tried it on 1.12.2 and flawless greenhouse not farming the hemp seeds
