### ISSUE TITLE
Server crashing: Reinforced furnace

### ISSUE THREAD

**Issue by RunAge** [SonarSonic/Calculator#227]
* Forge Version: forge-12.18.3.2254
 * Calculator Version: 1.10.2-3.1.9
 * SonarCore Version: 1.10.2-3.2.5
 * Multiplayer or Singleplayer:  Multiplayer
 * Crash Report Link: https://gist.github.com/cfc6f993e55ded63862dd134fb8d575b
 * Affected Features: World
 * Description: Server crash when reinforced furnace have last item to smelt.
 * Modpack: Onioncraft on curse

**Comment by MysticAura** [comment]
Having the same issue. 

Hoping Calc gets fixed soon, all the server crashes in the past few months are very uncharacteristic and may force me to remove it from NEoA before published. Which would be a shame since it's such a great mod I wanted to promote.
[Crash Log](http://pastebin.com/JqkbCmyy)

**Comment by AEnterprise** [comment]
are there any mods present that alter smelting recipes? does this heapen with any smelting recipe or all just specific recipes?

**Comment by RunAge** [comment]
probably any because when I smelt iron then on last iron ore server crash and when I smelt logs to charcoal on last log server crash

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by MysticAura** [comment]
Just figured out what it seems to be doing. After it's smelted it's last
item, it tries to smelt another (which doesn't exist) and when the process
completes the game crashes. Still happening in 3.2.0

**Comment by MysticAura** [comment]
MC: 1.10.2
Forge: 2254
Mod: Calculator-1.10.2-3.2.0
Lib: SonarCore-1.10.2-3.2.6

Still crashing on the last item. However, this log is slightly different than the other
[Crash Log](http://pastebin.com/NqgZNcR3)

**Comment by SonarSonic** [comment]
Fixed in dev
