### ISSUE TITLE
Storage chamber stack overflow

### ISSUE THREAD

**Issue by bobbobkilu** [SonarSonic/Calculator#285]
* Forge Version: 1.10.2-12.18.3.2477
 * Calculator Version: 1.10.2-3.2.5
 * SonarCore Version: 1.10.2-329
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: None
 * Affected Features: Storage Chamber
 * Description: Non-crashing stack overflow in circuit itemstack.

Storage chamber does not prevent items from being inserted into a full stack, such that adding an circuit to a stack of size 127 causes a stack overflow, creating a stack of size -127.
 All functionality is maintained correctly, except that items can be removed as a single stack (seeing as a negative stacksize is less than 1) 
This occurs from both manual and automatic insertion.

Should be a relatively easy fix at least. Good luck with your mod!

**Comment by xilni** [comment]
It seems to still keep its count when the overflow wraps around back to positive numbers (past 255) and circuits are still able to be removed and inserted so no danger there so far.

**Comment by cdude20** [comment]
Sorry to bring this back from the dead. We are playing age of engineering on 1.10 and I was having the same stack overflow problem in the storage chamber. The One Probe still showed correct values. However, when one of the circuits hit 1024 count, the system broke and no more circuits could be inserted. It also began to cause massive tick drops. Once I managed to pull enough circuits out to drop below 1000 for that circuit, the tick drops went away and I was able to use the chamber again.

**Comment by jaxx0rr** [comment]
so the storage chamber has NEGATIVE VALUES in my game... what is up with that ?
I'm livid right now...

**Comment by AEnterprise** [comment]
there is an issue with how it stores data, it doesn't check if there is room for the circuit correctly, the data type it stores the value in is limited in what it can store, if it is increased beyond its limit then the values go into the negative because the data is no longer valid and it mis-interprets it

**Comment by jaxx0rr** [comment]
yep I understand it .. and it probably makes me even more furious coz i am a programmer myself :D .. probably fixed in last version but I just used cheats to fix it.. (inserted 4x100 circuits) ... Age of Engeneering is a bltch as is.. not many bugs tho but this one .. cheers

**Comment by AEnterprise** [comment]
it probably isn't fixed yet, this mod isn't under very active development atm sadly
